//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DarkHtmlViewerBasicDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DarkHtmlViewerBasicDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;{htmlResDir}bootstrap.min.css&quot;
        ///        rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;h1 class=&quot;mt-4&quot;&gt;Home page&lt;/h1&gt;
        ///        &lt;p&gt;Hello there, this is a home page!&lt;/p&gt;
        ///
        ///        &lt;p&gt;&lt;strong&gt;Table of contents&lt;/strong&gt;&lt;/p&gt;
        ///        &lt;ul&gt;
        ///            &lt;li&gt;&lt;a href=&quot;section1&quot;&gt;Super cool looking code!&lt;/a&gt;&lt;/li&gt;
        ///            &lt;li&gt;&lt;a href=&quot;section2&quot;&gt;What the hell are NFTs?&lt;/a&gt;&lt;/li&gt;
        ///        &lt;/ul&gt;
        ///
        ///        &lt;h2 id=&quot;section1&quot;&gt;Super cool looking code!&lt;/h2&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;{htmlResDir}bootstrap.min.css&quot;
        ///        rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;h1 class=&quot;mt-4&quot;&gt;Super cool looking code!&lt;/h1&gt;
        ///        &lt;p&gt;Hello there, this is a page about super cool looking code.&lt;/p&gt;
        ///
        ///        &lt;p&gt;&lt;a class=&quot;btn btn-primary&quot; href=&quot;gotoHome&quot;&gt;Go back to home page&lt;/a&gt;&lt;/p&gt;
        ///
        ///        &lt;p&gt;Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor illum illo dolore reiciendis minus labore
        ///            vitae nobis? Eaque har [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string page1 {
            get {
                return ResourceManager.GetString("page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;link href=&quot;{htmlResDir}bootstrap.min.css&quot;
        ///        rel=&quot;stylesheet&quot;&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot;container&quot;&gt;
        ///        &lt;h1 class=&quot;mt-4&quot;&gt;What the hell are NFTs?&lt;/h1&gt;
        ///        &lt;p&gt;Hello there, this is a page about NFTs.&lt;/p&gt;
        ///
        ///        &lt;p&gt;&lt;a class=&quot;btn btn-primary&quot; href=&quot;gotoHome&quot;&gt;Go back to home page&lt;/a&gt;&lt;/p&gt;
        ///
        ///        &lt;p&gt;Lorem, ipsum dolor sit amet consectetur adipisicing elit. Dolor illum illo dolore reiciendis minus labore
        ///            vitae nobis? Eaque harum voluptatem cum en [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string page2 {
            get {
                return ResourceManager.GetString("page2", resourceCulture);
            }
        }
    }
}
